kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # Isso vai desabilitar o CNI padrão do Kind, para então podermos instalar o Calico
  podSubnet: 192.168.0.0/16
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker